# Generated by Django 5.1.7 on 2025-03-25 04:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='code',
        ),
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.AddField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
