# Generated by Django 5.1.7 on 2025-03-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_college_code_remove_college_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name'], 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='orgmember',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(verbose_name='Date Joined'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('name', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='orgmember',
            unique_together={('student', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'college')},
        ),
    ]
